title: Nepal Online School
email: nepalonlineschool@gmail.com
description: >-
  Nepal Online School(NOS) is a non-profit digital learning platform working for
  free education in Nepal. With dedicated and hardworking mentors, we have
  created quality videos from academics to yoga. Learning is experiencing
  and NOS team wants everyone to feel that.
baseurl: ""
url: "https://nepalonlineschool.org"

google_analytics: # your google analytics id

# Build settings
markdown: kramdown
